### ISSUE TITLE
issue about phpx.x-fpm-tex.sock

### ISSUE THREAD

**Issue by niudai** [parpalak/i.upmath.me#12]
this is a amazing latex renderer, but when I try to deploy to my server, I cannot find `php-fpm-tex.sock` in my host. I know I should start `php-fpm` service to enable this:

```
	upstream php-sock {
		server unix:/var/run/php/php7.3-fpm.sock;
	}
```

but for php7.3-fpm-tex.sock, I don't know where to find this CGI service, what's this? where can I find it? 

Sorry for this silly question.

**Comment by parpalak** [comment]
In my case `php7.3-fpm.sock` is a unix socket for a custom PHP-FPM worker pool. I use it to separate PHP processes serving usual http requests and requests for generating latex equations.

You have to configure the pool or to use a default PHP-FPM pool and socket depending on your requirements. You can refer to this guide when setting up PHP and NGINX: https://www.linode.com/docs/web-servers/nginx/serve-php-php-fpm-and-nginx/
