### ISSUE TITLE
Prefered way to install TexLive

### ISSUE THREAD

**Issue by jimisens** [parpalak/i.upmath.me#17]
Hello,
I'm trying this fantastic library but we found some problems with margin and fonts, some svg are not displaying well. 
I actually don't know which is the best way to install TexLive in linux ?  When you say "TeX Live. I prefer a full installation and disabling write18 support"

From TexLive site i have :
wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl.zip
unzip ./install-tl.zip -d install-tl 

But these is not working well

Can i do something lilke : sudo apt-get install texlive-full ? 

Thanks!

**Comment by parpalak** [comment]
You can try to use LaTeX from apt as well. It should work fine.

**Comment by jimisens** [comment]
Thank you, i will try today.
