### ISSUE TITLE
">" and  "<"  printing as "gt;"  "lt;" \begin{aligned} prints "amp;"

### ISSUE THREAD

**Issue by GuillermoBasoco** [parpalak/i.upmath.me#18]
Hi @parpalak,

I've tested this excelent library with two latex versions: 

- texlive2021 (dvisvgm 2.11.1)
- texlive2019 (dvisvgm 2.8.1)

In both cases, I found a problem with the ">" "<" characters and the \begin{aligned} directive. For example, the following formula is printed as follows:

$$
\begin{equation}
\begin{aligned}
F ={} & \{F_{x} \in F_{c} : (|S| > |C|) \\
& \cap (\mathrm{minPixels} < |S| < \mathrm{maxPixels}) \\
& \cap (|S_{\mathrm{conected}}| > |S| - \epsilon)\}
\end{aligned}
\end{equation}
$$

![image](https://user-images.githubusercontent.com/13950522/120675989-337f9780-c45b-11eb-8b86-07477a62caa5.png)

In the Upmath editor, it shows perfectly:

![image](https://user-images.githubusercontent.com/13950522/120676202-675abd00-c45b-11eb-93c5-768c7d07d710.png)

Tried forcing mathmode and also disabling \write18 with no success.

Thanks.

**Comment by parpalak** [comment]
I think the problem is somewhere in integration between your software and Upmath. There are unnecessary escaping of the equation text before it goes to the Upmath. There is nothing wrong with LaTeX version and \write18 in your case.

**Comment by GuillermoBasoco** [comment]
Thanks @parpalak ! It was a problem with the htmlspecialchars() function. Problem solved
