### ISSUE TITLE
Suggest adding the function `\mathscr` from `mathrsfs` package

### ISSUE THREAD

**Issue by hbghlyj** [parpalak/i.upmath.me#29]
I'm trying to use \mathscr in my documents, but it doesn't show up as expected. I would like to suggest adding the function `\mathscr` for capital letters from the `mathrsfs` package.
```tex
\usepackage{mathrsfs}
\mathscr{ABCDEFGHIJKLMNOPQRSTUVWXYZ}
```

Expected:
![image](https://github.com/user-attachments/assets/4abfea12-a941-4429-abae-689cf15a4ae9)

I searched on math.stackexchange and found that `\mathscr` is a common function used by many users. Here is the link to the search results:
https://math.stackexchange.com/search?q=mathscr

![image](https://github.com/user-attachments/assets/fbcac67b-7324-47b6-b7b4-567597204dd3)

**Comment by parpalak** [comment]
Looks nice, I've added support.
