### ISSUE TITLE
Change absolute resource path to relative resource path

### ISSUE THREAD

**Issue by walkerlala** [parpalak/i.upmath.me#3]
I would suggest change those absolute resource paths like:

    href="/css/some-css-file
    href="/js/some-js-file

to some relative paths like:

    href="./css/some-css-file
    href="./js/some-js-file

in case somebody don't want to make `tex.s2cms.ru/www` their document root.

**Comment by parpalak** [comment]
The code in this repository is not supposed to be distributed. So I'm not going to change the paths now.
